apiVersion: v1
kind:  Service
metadata:
#debe tener el mismo nombre del  deployment
  name: active-mq
spec:
  ports:
  - name: dashboard
    port: 8161
    targetPort: 8161
    protocol: TCP
  - name: openwire
    port: 61616
    targetPort: 61616
    protocol: TCP
#  - name: amqp
#    port: 5672
#    targetPort: 5672
#    protocol: TCP
  - name: stomp
    port: 61613
    targetPort: 61613
    protocol: TCP
#  - name: mqtt
#    port: 1883
#    targetPort: 1883
#    protocol: TCP
  selector:
  #seleccionamos la etiqueta la cual va apuntarle el servicio
    rol: active-mq
  type: LoadBalancer